#!/usr/bin/with-contenv /bin/bash

IFS=':' read -r ip port <<<"${SYNCTHING_WEBUI_PORT}"
[[ -z "${port}" ]] && port="${ip}"

# if syncthing's webinterface is up we assume everything is fine
curl -s -o /dev/null -w "%{http_code}" --connect-timeout 2 \
    http://localhost:"${port:-8384}"
