#!/usr/bin/with-contenv /bin/bash
SYNCTHING_API_KEY=$(cat /.apikey)
DOCKER_IP=$(hostname -i)

exec runsuer --pty --user runuser -- \
    syncthing -home=/syncthing \
    -gui-address="${SYNCTHING_WEBUI_ADDRESS:-${DOCKER_IP}}:${SYNCTHING_WEBUI_PORT}" \
    -gui-apikey="${SYNCTHING_API_KEY}" -no-browser
