---
name: Publish Docker image
#on:
#  release:
#    types: [published]
# only build on tags, for testing use manual workflow_dispatch
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker images to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2.4.0
        with:
          images: ghcr.io/azmodude/syncthing
      - name: Get commit SHA
        id: get_sha
        run: echo "COMMIT_SHA=${GITHUB_SHA:10}" >> $GITHUB_ENV
      - name: Set ENV variables from supplied .env file
        run: cat .env >> $GITHUB_ENV
      - name: Build and Push Image to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            S6_OVERLAY_VERSION=${{ env.S6_OVERLAY_VERSION }}
            COMMIT_SHA=${{ env.COMMIT_SHA }}
            NZBGET_VERSION=${{ env.NZBGET_VERSION }}
            NZBGET_RAR_VERSION=${{ env.NZBGET_RAR_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          # push: true
